name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Test build Server RS Jakut
      run: cd rs-jakut && go build Server-JAKUT.go

    - name: Test build Server RS Jakpus
      run: cd rs-jakpus && go build Server-JAKPUS.go
